Method descriptions update
AVSystem/scex pull request #24
Opened 2023-08-03 15:07 UTC by mkrolavs

Updates for descriptions of date, format, string, enriched date.

2023-08-04 14:14 UTC, pzareba22 requested changes

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/StringNetworkOps.scala
> +  @Documentation("Returns 0 if the addresses provided are equal, -1 if `ip1` < `ip2` or 1 if `ip1` > `ip2`.")
I'd suggest a naming convention more along the lines of "this" and "other", rather than "ip1" and "ip2"

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/StringNetworkOps.scala
> +  @Documentation("Returns true if the string is an IPv4 address which belongs to the subnet provided as the `subnetWithMask` argument. Use CIDR notation for the argument, e.g. `10.8.0.0/16`.")
maybe split this into 2 lines

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/StringMiscOps.scala
> +  @Documentation("Prepends this string with given `padding`, repeated or trimmed if needed. Number of characters in the output corresponds to `desiredLength`.")
this method doesn't trim

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/StringMiscOps.scala
> +  @Documentation("Appends given `padding` to this string, repeated or trimmed if needed. Number of characters in the output corresponds to `desiredLength`.")
doesn't trim aswell

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/DateUtil.java
> +    @Documentation("Returns the provided value in milliseconds as a date.")
Maybe add information that the value is actually a distance from 01.01.1970 in milliseconds

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/FormatUtil.java
> +    @Documentation("Transforms the provided `value` into a common scale. `siCompliance` set to `true` means a decimal base is used (1000), otherwise binary (1024). Select unit via `inputUnitIndex` in
maybe split into several lines

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/NetUtil.java
> +    @Documentation("Returns true if the value of `ip` argument belongs to the subnet provided as the `subnetWithMask` argument. Use CIDR notation for the `subnetWithMask` argument, e.g. `10.8.0.0/16`
split into multiple lines please

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/NetUtil.java
> +    @Documentation("Returns 0 if the addresses provided are equal, -1 if `ip1` < `ip2` or 1 if `ip1` > `ip2`.")
as in `StringNetworkOps.scala`

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/StringUtil.java
> +    @Documentation("Appends `padStr` (repeated or trimmed if needed) to the `str` string. Number of characters in the output corresponds to `size`.")
as above - these methods don't do trimming

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/StringUtil.java
> +    @Documentation("Returns all parts of a dot-separated string following the part indicated by `from` value. `Dot` boolean value determines if a dot is added to the output, e.g. string.slice('a.b.c.
please also mention the `to` value

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/StringUtil.java
> +    @Documentation("Returns the `source` string with `InternetGatewayDevice.` or `Device.` parts removed.")
it might be worth mentioning that this method only removes the `InternetGatewayDevice.` or `Device.` strings from the beginning of the input

2023-08-04 14:14 UTC, pzareba22 commented on scex-util/src/main/scala/com/avsystem/scex/util/function/StringUtil.java
> +    @Documentation("Returns the `str` string with whitespaces removed.")
consider adding the information that the whitespaces are removed from both ends of the string (the ones in the middle of the string are not)

2023-08-07 09:20 UTC, mkrolavs commented
@pzareba22 all comments addressed

2023-08-07 14:27 UTC, pzareba22 approved these changes
LGTM

2023-08-08 11:46 UTC, merged