Math util descriptions
AVSystem/scex pull request #25
Opened 2023-08-08 12:00 UTC by mkrolavs

Math util documentation

2023-08-22 10:56 UTC, pzareba22 requested changes

2023-08-22 10:56 UTC, pzareba22 commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +    on { m: scala.math.type =>
change this to ```m: math.`package`.type =>```, the current version doesn't compile

2023-08-22 10:56 UTC, pzareba22 commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.expm1 _ --> Attributes(documentation = "Return the Euler's number raised to the power of the `x` argument with one subtracted from it.")
I'd rephrase this. The method calculates `exp(x) - 1`, but this description could also be understood as `exp(x-1)`

2023-08-22 10:56 UTC, pzareba22 commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.floorMod(_: Long, _:Long) --> Attributes(documentation = "Returns the largest integer value less than or equal to the algebraic quotient, " +
This looks like a modulus instead of a quotient

2023-08-22 10:56 UTC, pzareba22 commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.getExponent(_: Float) --> Attributes(documentation = "Returns the size of unit in the last place of the `f` argument.")
The javadocs on the inner method say that it returns 'an unbiased exponent', why the change in the description?

2023-08-22 10:56 UTC, pzareba22 commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.rint _ --> Attributes(documentation = "Returns the closest floating point value that is equal to the integer for the `x` argument.")
maybe "... that is equal to a mathematical integer..."

2023-08-22 10:58 UTC, pzareba22 commented
Also, please fix formatting in the file

2023-08-28 11:15 UTC, halotukozak requested changes

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.abs(_: Double) --> Attributes(documentation = "Returns absolute value of `x` argument.")
no "the" before the (sic!) `x` argument; subsequent lines similarly

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.decrementExact(_: Int) --> Attributes(documentation = "Returns the `x` argument decremented by one.")
the pleonasm. Decrement is always by one; increment similarly

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.ceil _ --> Attributes(documentation = "Returns the smallest double value that is greater than or equal to the `x` argument and is equal to a mathematical integer.")
why ceiling is grouped with cbrt? What about grouping by definition (e.g. trigonometric functions together)

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.atan _ --> Attributes(documentation = "Returns the arc tangent of the `x` argument.")
for me, it's more popular to use arctan in the math world. But it's only my comment, arc tanget is also OK; subsequent lines similarly

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.floor _ --> Attributes(documentation = "Returns the largest integer value less than or equal to the `x` argument.")
`floor` returns double, use definition similar to `ceil`'s one

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.min(_: Double, _: Double) --> Attributes(documentation = "Returns the smaller of the provided `x` and `y` arguments.")
take a look at https://www.onemathematicalcat.org/algebra_book/online_problems/big_small.htm; subsequent lines similarly

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.nextDown(_: Double) --> Attributes(documentation = "Returns the floating-point value adjacent to the `d` argument in the direction of negative infinity.")
The description is consistent with the previous one, but what about simplifying it? 
"Returns the next smaller floating-point value to the `d` argument"; subsequent lines similarly

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.sqrt _ --> Attributes(documentation = "Returns the square root of the `x` argument.")
why `sqrt` function is... you know

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.rint _ --> Attributes(documentation = "Returns the closest floating point value that is equal to a mathematical integer for the `x` argument.")
why rint function is grouped with pow one?

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.subtractExact(_: Int, _: Int) --> Attributes(documentation = "Returns the difference of the `x` and `y` arguments.")
`between`? Or point out that it's x-y

2023-08-28 11:15 UTC, halotukozak commented on scex-core/src/main/scala/com/avsystem/scex/presentation/MathAttributes.scala
> +      m.ulp(_: Double) --> Attributes(documentation = "Returns the size of an ulp (unit in the last place) of the `x` argument.")
I'd make it shorter, like: "Returns the size of a unit in the last place of the `x` argument." ; subsequent lines similarly

2023-08-28 16:01 UTC, merged

2023-08-28 16:01 UTC, halotukozak commented
LGTM