Avoid race condition in Reporter errorsBuilder
AVSystem/scex pull request #36
Opened 2024-05-21 13:18 UTC by anetaporebska

2024-05-23 08:21 UTC, sebaciv requested changes

2024-05-23 08:21 UTC, sebaciv commented on scex-core/src/main/scala/com/avsystem/scex/compiler/ScexCompiler.scala
>      }
Suggestion: add resetAndClearErrors method to avoid repeating subsequent `reset` and `clearError` calls in  other places

2024-05-23 08:21 UTC, sebaciv commented on scex-core/src/test/scala/com/avsystem/scex/compiler/MultipleEvaluationsTest.scala
> +  test("Multiple evaluations of invalid expressions should always fail") {
Add test case with mixed correct and incorrect expressions

Also check corner case, when invalid expression is the last one before reaching `settings.resetAfterCount` and next expression is valid

2024-06-26 11:43 UTC, anetaporebska commented
Closing since it touches core scex functionalities and the regression risk is too high

2024-06-26 11:43 UTC, closed without merging